server:
  port: 8010
spring:
  application:
    # 指定注册到eureka server上的服务名称
    name: cloud-buy-service
eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      defaultZone: http://facemeng:facemeng123@localhost:8761/eureka/
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true
---
feign:
  client:
    config:
      default:
        loggerLevel: basic
        connectTimeout: 3000
        readTimeout: 3000
      cloud-user-service:
        connectTimeout: 3000
        readTimeout: 3000
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled: true

#cloud-user-service:
#  ribbon:
#    ConnectTimeout: 3000
#    ReadTimeout: 6000
#    OkToRetryOnAllOperations: false
#    MaxAutoRetriesNextServer: 2
#    MaxAutoRetries: 0

ribbon:
#  ConnectTimeout: 3000
#  ReadTimeout: 4000
#  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 0
  MaxAutoRetries: 0
  eager-load:
    clients: cloud-user-service
    enabled: true

hystrix:
  threadpool:
    default:
      maxQueueSize: 20
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          #是否开启超时熔断
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000 #断路器超时时间，默认1000ms

management:
  endpoint:
    health:
      # 是否展示健康检查详情
      show-details: always
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream'
---
logging:
  level:
    com.wpline.cloud: DEBUG
#    com.netflix: DEBUG